// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// get_forms_grass_enum
Rcpp::IntegerVector get_forms_grass_enum();
RcppExport SEXP _rgeomorphon_get_forms_grass_enum() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_forms_grass_enum());
    return rcpp_result_gen;
END_RCPP
}
// get_forms_matrix_cpp
Rcpp::NumericMatrix get_forms_matrix_cpp(int num_forms);
RcppExport SEXP _rgeomorphon_get_forms_matrix_cpp(SEXP num_formsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type num_forms(num_formsSEXP);
    rcpp_result_gen = Rcpp::wrap(get_forms_matrix_cpp(num_forms));
    return rcpp_result_gen;
END_RCPP
}
// geomorphons_cpp_worker
Rcpp::List geomorphons_cpp_worker(Rcpp::NumericMatrix elevation, double search, double skip, double flat_angle_deg, double dist, std::string comparison_mode, double tdist, bool use_meters, double x_res_dem, double y_res_dem, int forms, int ternary, int positive, int negative, double nodata);
RcppExport SEXP _rgeomorphon_geomorphons_cpp_worker(SEXP elevationSEXP, SEXP searchSEXP, SEXP skipSEXP, SEXP flat_angle_degSEXP, SEXP distSEXP, SEXP comparison_modeSEXP, SEXP tdistSEXP, SEXP use_metersSEXP, SEXP x_res_demSEXP, SEXP y_res_demSEXP, SEXP formsSEXP, SEXP ternarySEXP, SEXP positiveSEXP, SEXP negativeSEXP, SEXP nodataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type elevation(elevationSEXP);
    Rcpp::traits::input_parameter< double >::type search(searchSEXP);
    Rcpp::traits::input_parameter< double >::type skip(skipSEXP);
    Rcpp::traits::input_parameter< double >::type flat_angle_deg(flat_angle_degSEXP);
    Rcpp::traits::input_parameter< double >::type dist(distSEXP);
    Rcpp::traits::input_parameter< std::string >::type comparison_mode(comparison_modeSEXP);
    Rcpp::traits::input_parameter< double >::type tdist(tdistSEXP);
    Rcpp::traits::input_parameter< bool >::type use_meters(use_metersSEXP);
    Rcpp::traits::input_parameter< double >::type x_res_dem(x_res_demSEXP);
    Rcpp::traits::input_parameter< double >::type y_res_dem(y_res_demSEXP);
    Rcpp::traits::input_parameter< int >::type forms(formsSEXP);
    Rcpp::traits::input_parameter< int >::type ternary(ternarySEXP);
    Rcpp::traits::input_parameter< int >::type positive(positiveSEXP);
    Rcpp::traits::input_parameter< int >::type negative(negativeSEXP);
    Rcpp::traits::input_parameter< double >::type nodata(nodataSEXP);
    rcpp_result_gen = Rcpp::wrap(geomorphons_cpp_worker(elevation, search, skip, flat_angle_deg, dist, comparison_mode, tdist, use_meters, x_res_dem, y_res_dem, forms, ternary, positive, negative, nodata));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rgeomorphon_get_forms_grass_enum", (DL_FUNC) &_rgeomorphon_get_forms_grass_enum, 0},
    {"_rgeomorphon_get_forms_matrix_cpp", (DL_FUNC) &_rgeomorphon_get_forms_matrix_cpp, 1},
    {"_rgeomorphon_geomorphons_cpp_worker", (DL_FUNC) &_rgeomorphon_geomorphons_cpp_worker, 15},
    {NULL, NULL, 0}
};

RcppExport void R_init_rgeomorphon(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
