// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// geomorphons_cpp_worker
Rcpp::List geomorphons_cpp_worker(Rcpp::NumericMatrix elevation, double search, double skip, double flat_angle_deg, double dist, std::string comparison_mode, double tdist, bool use_meters, double x_res_dem, double y_res_dem, double nodata);
RcppExport SEXP _rgeomorphon_geomorphons_cpp_worker(SEXP elevationSEXP, SEXP searchSEXP, SEXP skipSEXP, SEXP flat_angle_degSEXP, SEXP distSEXP, SEXP comparison_modeSEXP, SEXP tdistSEXP, SEXP use_metersSEXP, SEXP x_res_demSEXP, SEXP y_res_demSEXP, SEXP nodataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type elevation(elevationSEXP);
    Rcpp::traits::input_parameter< double >::type search(searchSEXP);
    Rcpp::traits::input_parameter< double >::type skip(skipSEXP);
    Rcpp::traits::input_parameter< double >::type flat_angle_deg(flat_angle_degSEXP);
    Rcpp::traits::input_parameter< double >::type dist(distSEXP);
    Rcpp::traits::input_parameter< std::string >::type comparison_mode(comparison_modeSEXP);
    Rcpp::traits::input_parameter< double >::type tdist(tdistSEXP);
    Rcpp::traits::input_parameter< bool >::type use_meters(use_metersSEXP);
    Rcpp::traits::input_parameter< double >::type x_res_dem(x_res_demSEXP);
    Rcpp::traits::input_parameter< double >::type y_res_dem(y_res_demSEXP);
    Rcpp::traits::input_parameter< double >::type nodata(nodataSEXP);
    rcpp_result_gen = Rcpp::wrap(geomorphons_cpp_worker(elevation, search, skip, flat_angle_deg, dist, comparison_mode, tdist, use_meters, x_res_dem, y_res_dem, nodata));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rgeomorphon_geomorphons_cpp_worker", (DL_FUNC) &_rgeomorphon_geomorphons_cpp_worker, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_rgeomorphon(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
