# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_forms_grass_enum <- function() {
    .Call('_rgeomorphon_get_forms_grass_enum', PACKAGE = 'rgeomorphon')
}

get_forms_matrix_cpp <- function(num_forms) {
    .Call('_rgeomorphon_get_forms_matrix_cpp', PACKAGE = 'rgeomorphon', num_forms)
}

geomorphons_cpp_worker <- function(elevation, search, skip, flat_angle_deg, dist, comparison_mode, tdist, use_meters, x_res_dem, y_res_dem, forms, ternary, positive, negative, nodata) {
    .Call('_rgeomorphon_geomorphons_cpp_worker', PACKAGE = 'rgeomorphon', elevation, search, skip, flat_angle_deg, dist, comparison_mode, tdist, use_meters, x_res_dem, y_res_dem, forms, ternary, positive, negative, nodata)
}

